version: 2

sources:
    - name: staging
      database: dataengineeringzoocamp
      schema: trips_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata
        - name: fhv_tripdata_2019_bq